import express from "express";
import cors from "cors";
import history from "connect-history-api-fallback";
import dotenv from "dotenv";
import bodyParser from "body-parser";
import { ChatGPTAPI } from "chatgpt";
import path from "path";
import url from "url";
import https from "https";
import fsync from "fs";

dotenv.config();

const __dirname = url.fileURLToPath(new URL(".", import.meta.url));

// We use 3 super-secret 🔐 prompts generated by prompt engineering techniques to train ChatGPT to do the following:

// This is the function that will be called to check if the input text contains bias, and return a boolean value. ChatGPT has been instructed to follow the bias detection prompt.
const biasPresent = async (msg) => {
	const api = new ChatGPTAPI({
		apiKey: process.env.OPENAI_API_KEY,
		systemMessage: `${process.env.BIAS_DETECTION_PROMPT}`,
	});

	const res = await api.sendMessage(msg);

	// Errors out if the response is not 1 or 0, but it has been correct 100% of the time.
	if (res.text == "1") return true;
	else if (res.text == "0") return false;
	else return "Error Occurred";
};

// This is the function that will be called to create guidance for the user. ChatGPT has been instructed to follow the narration prompt.
const creatGuidance = async (speaker, situation) => {
	const api = new ChatGPTAPI({
		apiKey: process.env.OPENAI_API_KEY,
		systemMessage: `${process.env.NARRATION_PROMPT}`,
	});

	// The user's input is passed to the function as a set of "speaker" and "situation" variables to provide context to ChatGPT so it follows the originial Narration Prompt instructions.

	// The "guidance" endpoint provides a response that is more tied to the speaker, and shows what and how they would respond if they were in the same situation.
	const res = await api.sendMessage(
		`Create a narrative dialogue with "${speaker}" thinking about the situation of bias "${situation}"`
	);

	return res.text;
};

// This is the function that will be called to create empathy for the user. ChatGPT has been instructed to follow the narration prompt.
const createEmpathy = async (speaker, situation) => {
	const api = new ChatGPTAPI({
		apiKey: process.env.OPENAI_API_KEY,
		systemMessage: `${process.env.NARRATION_PROMPT}`,
	});

	// The user's input is passed to the function as a set of "speaker" and "situation" variables to provide context to ChatGPT so it follows the originial Narration Prompt instructions.

	// The "empathy" endpoint provides personable, casual but supportive response from the speaker's talking style, as if they we sitting across from each other.
	const res = await api.sendMessage(
		`Create a response in the style of "${speaker}" for the situation "${situation}"`
	);

	return res.text;
};

const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(
	cors({
		origin: process.env.FRONTEND_URL,
		optionsSuccessStatus: 200,
		credentials: true,
	})
);
app.use((req, res, next) => {
	res.header(
		"Access-Control-Allow-Headers",
		"x-access-token, Origin, Content-Type, Accept"
	);
	next();
});
app.use(history());

app.post("/guidance", async (req, res) => {
	console.log(req.body.chat);
	const presence = await biasPresent(req.body.chat);
	if (presence == "Error Occurred") res.status(500).send(presence);
	else {
		if (presence) {
			const guidance = await creatGuidance(
				req.body.speaker,
				req.body.chat
			);
			res.send(guidance);
		} else res.send("Please input a situation of bias.");
	}
});

app.post("/empathy", async (req, res) => {
	console.log(req.body.chat);
	const presence = await biasPresent(req.body.chat);
	if (presence == "Error Occurred") res.status(500).send(presence);
	else {
		if (presence) {
			const empathy = await createEmpathy(
				req.body.speaker,
				req.body.chat
			);
			res.send(empathy);
		} else res.send("Please input a situation of bias.");
	}
});

app.use("/", async (req, res) => {
	res.send("Hello, world!");
});

https
	.createServer(
		{
			cert: fsync.readFileSync(path.join(__dirname, "certificate.crt")),
			key: fsync.readFileSync(path.join(__dirname, "private.key")),
		},
		app
	)
	.listen(3000);
console.log("Listening at http://localhost:3000");
